/**
*
* Check out easing references at https://easings.net/
*/
public enum Easings
{
    Linear,
    EaseInSin,
    EaseInQuad,
    EaseInQuint,
    EaseInCubic,
    EaseInQuart,
    EaseInExpo,
    EaseInCirc,
    EaseInBack,
    EaseInQuartic,
    EaseInOutSine,
    EaseInOutCubic,
    EaseInOutQuart,
    EaseInOutQuint,
    EaseInOutExpo,
    EaseInOutCirc,
    EaseInOutBack,
    EaseInOutQuadratic,
    EaseInOutQuad,
    EaseInOutElastic,
    EaseInOutBounce,
    EaseOutElastic,
    EaseOutBounce,
    EaseOutCubic,
    EaseOutQuint,
    EaseOutSine,
    EaseOutQuad,
    EaseOutQuart,
    EaseOutExpo,
    EaseOutCirc,
    EaseOutBack,
    EaseOutQuadratic,
    EaseOutQuartic
}